### ISSUE TITLE
Inventory backup copies of a submission

### ISSUE THREAD

**Issue by rcurrie** [ga4gh/cgtd#7]
Count the copies of a submission within the extended network of peers to see if there is more then one copy present. This will ensure that even if a server goes down or even disappears that the content it published will still be able to be accessed by multihash. Crawlers, or curation nodes should reference via multihash (vs. ipns) so that they can still server content even if a server is gone (and therefore its ipns addresses gone).

**Comment by brainstorm** [comment]
Do we need this? I thought that de-duplication was included within the protocol/spec, right?:

![skarmavbild 2016-10-03 kl 18 21 01](https://cloud.githubusercontent.com/assets/175587/19044834/32278000-8996-11e6-8abb-d1f6a384290c.png)

**Comment by rcurrie** [comment]
Should probably change the title of this issue - what I'm getting at is more from a backup perspective - is this blob mirrored in more then just my server. Simple plan would be for any peer to 'pin' all the hashes from the other server. That way there is at least one other copy. Say a server disappears from the network. Their ipns address will no longer be able to be resolve. But, a search engine say that stores just the multihashes will still be able to reliably return results as well as get to the underlying files as long as some other server has at least one copy.

**Comment by brainstorm** [comment]
Ah, gotcha now, strictly related with issue https://github.com/ga4gh/cgtd/issues/6 then.

**Comment by rcurrie** [comment]
Closing in favor of putting this under #6
